import Head from 'next/head'
import styled from 'styled-components'

// Components
import HeroSlider from '../components/HeroSlider'
import GaleriePreview from '../components/pages-components/GaleriePreview'
import QuickOverview from '../components/pages-components/QuickOverview'
import TeamPresentation from '../components/pages-components/TeamPresentation'
import Section from '../components/Section'

export default function Home() {
  return (
    <>
      <Head>
        <title>Monteiro maconnerie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HeroSlider idToGo="quick-overview" />
        <Section id="quick-overview">
          <QuickOverview />
        </Section>
        <Section id="team-presentation" darker>
          <TeamPresentation />
        </Section>
        <Section id="team-presentation" darker fullSize>
          <GaleriePreview />
        </Section>
      </main>
    </>
  )
}
