import Head from 'next/head'

// Components
import HeroSlider from '../components/HeroSlider'
import CustomersReviews from '../components/pages-components/CustomersReviews'
import GaleriePreview from '../components/pages-components/GaleriePreview'
import QuickOverview from '../components/pages-components/QuickOverview'
import TeamPresentation from '../components/pages-components/TeamPresentation'
import Section from '../components/Section'

export default function Home() {
  return (
    <>
      <Head>
        <title>Monteiro maconnerie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HeroSlider idToGo="presentation-rapide" />
        <Section id="presentation-rapide">
          <QuickOverview />
        </Section>
        <Section id="presentation-equipe" darker>
          <TeamPresentation />
        </Section>
        <Section id="previsualisation-galerie" darker fullSize>
          <GaleriePreview />
        </Section>
        <Section id="avis-clients">
          <CustomersReviews />
        </Section>
      </main>
    </>
  )
}
