import Head from 'next/head'
import HeroSlider from '../components/HeroSlider'
import Section from '../components/Section'

export default function Home() {
  return (
    <>
      <Head>
        <title>Monteiro maconnerie</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HeroSlider idToGo="quick-overview" />
        <Section id="quick-overview">
          <>
            sheeeshhh adawd aw
            <div>d</div>
          </>
        </Section>
      </main>
    </>
  )
}
